title: Cory Sulpizi
logo: "/images/Cory.png?raw=true" 
description: > 
  M.Eng, University of Toronto<br><br>
  Interest in data science, machine learning, statistical inference<br><br>
  e: cory.sulpizi@mail.utoronto.ca

footer-links:
  email: "cory.sulpizi@mail.utoronto.ca"

theme: jekyll-theme-minimal
#google_analytics: <tracking-id>
