title: Cory Sulpizi
logo: "/images/Cory.png?raw=true" 
description: > 
  M.Eng Graduate from the University of Toronto<br>
  Interest in data science, machine learning, statistical inference
  
theme: jekyll-theme-minimal
#google_analytics: <tracking-id>
