title: Cory Sulpizi
logo: "/images/Cory.png?raw=true" 
description: > 
  M.Eng Graduate from UofT<br>
  Focus on data science, machine learning, statistical inference
  
theme: jekyll-theme-minimal
#google_analytics: <tracking-id>
