title: Cory Sulpizi
logo: "/images/Cory.png?raw=true" 
description: > 
  M.Eng, University of Toronto<br>
  -----------------------------------<br>
  Prediction, pattern recognition, statistical inference and machine learning<br>
  e: cory.sulpizi@mail.utoronto.ca<br>
  <a href="https://github.com/csulpizi">github profile</a>

footer-links:
  email: "cory.sulpizi@mail.utoronto.ca"

theme: jekyll-theme-architect

sass:
  style: :expanded
#google_analytics: <tracking-id>
